production_sites:
  - target_products:
      - [1, "boiler"]
      - [1, "steam-engine"]
      - [1, 'offshore-pump']
max_assemblers: 16
solver:
  time_limit: 30
transformations:
  - "building_speed_applier"
available_resources:
  - "minable_resources"
  - "basic_processing"
building_resolver_overrides:
  crafting: "assembling-machine-2"
  basic-crafting: "assembling-machine-2"
  crafting-with-fluid: "assembling-machine-2"
  advanced-crafting: "assembling-machine-2"
  chemistry: "chemical-plant"
  pulverising: "assembling-machine-2"
