target_products:
  - [ 1, fast-inserter]
max_assemblers: 32
inserter_type: "filter-inserter"
available_resources:
  - "minable_resources"
  - "basic_processing"
additional_resources:
  - "se-iron-ingot"
  - "se-copper-ingot"
output: "chest"
building_resolver_overrides:
  crafting: assembling-machine-3
  basic-crafting: assembling-machine-3
  crafting-with-fluid: assembling-machine-3
  advanced-crafting: assembling-machine-3
  chemistry: chemical-plant
  pulverising: assembling-machine-3
assembling_machine_modules:
  - productivity-module-2
  - productivity-module-2
  - productivity-module-2
  - productivity-module-2
beacon:
  type: small
  modules:
    - speed-module-3
    - speed-module-3
    - speed-module-3
    - speed-module-3
    - speed-module-3
    - speed-module-3
    - speed-module-3
    - speed-module-3
transformations:
  - name: 'building_speed_applier'
  - name: 'small_beacon'
    modules:
      - speed-module-3
      - speed-module-3
      - speed-module-3
      - speed-module-3
      - speed-module-3
      - speed-module-3
      - speed-module-3
      - speed-module-3
  - name: 'module_inserter'
    modules:
      - productivity-module-2
      - productivity-module-2
      - productivity-module-2
      - productivity-module-2


assembly_path: data/assembly_machine.json
recipe_path: data/recipes.json
