production_sites:
    - target_products:
       - [ 30, rail ]
       - [ 4, cargo-wagon ]
       - [1, locomotive ]
       - [ 1, fluid-wagon ]
       - [ 1, pump]
       - [ 1, electric-furnace]
       - [1, big-electric-pole]
    - target_products:
        - [1, logistic-chest-passive-provider]
        - [ 8, stack-filter-inserter ]
        - [ 4, assembling-machine-2 ]
        - [ 10, medium-electric-pole ]
        - [ 2, substation ]
    - target_products:
        - [ 8, arithmetic-combinator]
        - [ 2, constant-combinator]
        - [ 2, chemical-plant]
        - [ 2, oil-refinery]
        - [ 2, pumpjack]
        - [ 8, stack-inserter ]
max_assemblers: 24
solver:
  time_limit: 10
transformations:
  - building_speed_applier
available_resources:
  - "minable_resources"
  - "basic_processing"
building_resolver_overrides:
  crafting: assembling-machine-2
  basic-crafting: assembling-machine-2
  crafting-with-fluid: assembling-machine-2
  advanced-crafting: assembling-machine-2
  chemistry: chemical-plant
  pulverising: assembling-machine-2
