production_sites:
    - target_products:
       - [ 30, rail ]
       - [ 4, cargo-wagon ]
       - [1, locomotive ]
    - target_products:
        - [ 8, stack-filter-inserter ]
        - [ 4, assembling-machine-3 ]
    - target_products:
        - [ 8, arithmetic-combinator]
        - [ 2, constant-combinator]
        - [ 2, substation ]
    - target_products:
        - [ 10, pipe]
        - [ 16, fast-inserter]

max_assemblers: 24
available_resources:
  - "minable_resources"
  - "basic_processing"
additional_resources:
  - "se-iron-ingot"
  - "se-copper-ingot"
building_resolver_overrides:
  crafting: assembling-machine-3
  basic-crafting: assembling-machine-3
  crafting-with-fluid: assembling-machine-3
  advanced-crafting: assembling-machine-3
  chemistry: chemical-plant
  pulverising: assembling-machine-3
assembling_machine_modules:
  - productivity-module-2
  - productivity-module-2
  - productivity-module-2
  - productivity-module-2
beacon:
  type: small
  modules:
    - speed-module-3
    - speed-module-3
    - speed-module-3
    - speed-module-3
    - speed-module-3
    - speed-module-3
    - speed-module-3
    - speed-module-3
assembly_path: data/assembly_machine.json
recipe_path: data/recipes.json
