target_products:
  - [ 1, rgbspm ]
max_assemblers: 48
available_resources:
  - "minable_resources"
  - "basic_processing"
output: "chest"
inserter_type: "filter-inserter"
building_resolver_overrides:
  crafting: assembling-machine-2
  basic-crafting: assembling-machine-2
  advanced-crafting: assembling-machine-2
  chemistry: chemical-plant
  pulverising: assembling-machine-2
transformations:
  - name: 'building_speed_applier'
assembling_machine_modules:
  - productivity-module-2
  - productivity-module-2
  - productivity-module-2
  - productivity-module-2
beacon:
  type: small
  modules:
    - speed-module-3
    - speed-module-3
    - speed-module-3
    - speed-module-3
    - speed-module-3
    - speed-module-3
    - speed-module-3
    - speed-module-3
assembly_path: data/assembly_machine.json
recipe_path: data/recipes.json
