target_products:
  - [ 1, 'flying-robot-frame' ]
max_assemblers: 32
available_resources:
  - "minable_resources"
  - "basic_processing"
additional_resources:
  - "se-iron-ingot"
  - "se-copper-ingot"
output:
    type: "chest"
    liquids:
        - "lubricant"
        - "sulfuric-acid"
building_resolver_overrides:
  crafting: assembling-machine-3
  basic-crafting: assembling-machine-3
  crafting-with-fluid: assembling-machine-3
  advanced-crafting: assembling-machine-3
  chemistry: chemical-plant
  pulverising: assembling-machine-3
assembling_machine_modules:
  - productivity-module-3
  - productivity-module-3
  - productivity-module-3
  - productivity-module-3
beacon:
  type: small
  modules:
    - speed-module-3
    - speed-module-3
    - speed-module-3
    - speed-module-3
    - speed-module-3
    - speed-module-3
    - speed-module-3
    - speed-module-3
assembly_path: data/assembly_machine.json
recipe_path: data/recipes.json
