production_sites:
  - target_products:
      - [1, "rgbospm"]
max_assemblers: 56
solver:
  time_limit: 60
transformations:
  - "building_speed_applier"
  - module_inserter:
      - "productivity-module"
      - "speed-module"
available_resources:
  - "minable_resources"
  - "basic_processing"
assembling_machine_modules:
  - "speed-module"
  - "productivity-module"
building_resolver_overrides:
  crafting: "assembling-machine-2"
  basic-crafting: "assembling-machine-2"
  crafting-with-fluid: "assembling-machine-2"
  advanced-crafting: "assembling-machine-2"
  chemistry: "chemical-plant"
  pulverising: "assembling-machine-2"
