target_products:
  - [ 3, cargo-wagon ]
  - [8, locomotive ]
  - [ 1, fluid-wagon ]
#  - [ 8, stack-filter-inserter]
max_assemblers: 16
inserter_type: "filter-inserter"
available_resources:
  - "minable_resources"
  - "basic_processing"
additional_resources:
  - "se-iron-ingot"
  - "se-copper-ingot"
output: "chest"
transformations:
  - name: 'building_speed_applier'
building_resolver_overrides:
  crafting: assembling-machine-2
  basic-crafting: assembling-machine-2
  crafting-with-fluid: assembling-machine-2
  advanced-crafting: assembling-machine-2
  chemistry: chemical-plant
  pulverising: assembling-machine-2
assembling_machine_modules:
  - productivity-module-2
  - productivity-module-2
  - productivity-module-2
  - productivity-module-2
beacon:
  type: small
  modules:
    - speed-module-3
    - speed-module-3
    - speed-module-3
    - speed-module-3
    - speed-module-3
    - speed-module-3
    - speed-module-3
    - speed-module-3
assembly_path: data/assembly_machine.json
recipe_path: data/recipes.json
