production_sites:
  - target_products:
    - [1, "se-decontamination-facility"]
    - [1, "se-thruster-suit"]
    - [1, "se-lifesupport-facility"]
max_assemblers: 32
solver:
  time_limit: 15
transformations:
  - "building_speed_applier"
  - module_inserter:
      - "productivity-module"
      - "speed-module"
available_resources:
  - "minable_resources"
  - "basic_processing"
additional_resources:
  - "plastic-bar"
assembling_machine_modules:
  - "speed-module"
  - "productivity-module"
building_resolver_overrides:
  crafting: "assembling-machine-2"
  basic-crafting: "assembling-machine-2"
  crafting-with-fluid: "assembling-machine-2"
  advanced-crafting: "assembling-machine-2"
  chemistry: "chemical-plant"
  pulverising: "assembling-machine-2"
